### ISSUE TITLE
research how authentication(OAuth) & sessions will be managed

### ISSUE THREAD

**Issue by brijs** [brijs/ammasandra#4]
UI ---> backend, and backend ---> firebase interactions will need to be updated accordingly.

**Comment by brijs** [comment]
I ve figured this out. I have a working prototype that I deployed to heroku. Try it at https://ammasandra.herokuapp.com (currently only enabled for google+ oauth, but enabling facebook & others is quite straightforward now). we can discuss this in more details.

Note: Am using **Flask** (python) application framework for the server (combined with **gunicorn** as the web-server). Also using **https://github.com/sahat/satellizer** for oauth flow wrappers (javascript based).

deploying to **heroku** forced me to compile 'requirements.txt' ie list of dependent python packages. So it should be easier for you to clone the repo and install packages & get going. (i also set up newrelic (as a heroku add-on) which monitors site performance)

In my prototype, I m using local sqllite, but given firebase's python integration, we should be able to use firebase.

**Comment by saurabh1011** [comment]
cool . will take a look ..

**Comment by brijs** [comment]
the server code is in server/ subdir. 
client side code is in myApp/.
